### PR TITLE
fix issues 24, issues 25

### LINKED ISSUE #24: [Vue warn]: Invalid component name: "VirtualGrid$1". Component names should conform to valid custom element name in html5 specification.

### LINKED ISSUE #25: If the scrolling container is a div, only the first page is rendered, the rest is blank

### PR DESCRIPTION
**Pull request by gaodeng**
fix https://github.com/Mikescops/vue-virtual-grid/issues/25
fix https://github.com/Mikescops/vue-virtual-grid/issues/24

### CODE REVIEW

File: src/VirtualGrid.vue [hunk 1]
```diff
@@ -424,6 +436,7 @@ export default class VirtualGrid<P> extends Vue {
             <div
                 v-for="item in renderData.cellsToRender"
                 :key="item.id"
+                class="grid-item-wraper"
```
Comment (Mikescops) [inline src/VirtualGrid.vue:439]: what is the reason for this change?

File: package.json [hunk 2]
```diff
@@ -62,5 +63,8 @@
     "ts",
     "type",
     "types"
-  ]
+  ],
+  "dependencies": {
+    "scrollparent": "^2.0.1"
```
Comment (Mikescops) [inline package.json:68]: i'm not a big fan of adding a library like this, we can internalize the code so we know what's inside

File: src/VirtualGrid.vue [hunk 3]
```diff
@@ -394,6 +397,15 @@ export default class VirtualGrid<P> extends Vue {
     getElementOffset(element: Element) {
         return window.scrollY + element.getBoundingClientRect().top;
     }
+    getListenerTarget() {
```
Comment (Mikescops) [inline src/VirtualGrid.vue:400]: Can you provide an alternative version of the example that would be impacted by this change?

**Review by Mikescops — CHANGES_REQUESTED** [review]
Hello, 
Thanks for submitting this idea, I never thought about this use case. 
I requested a few changes and information. Among them, I'd like this library to be dependences free :smiley:

File: package.json (hunk 2 above)
Comment (gaodeng) [reply package.json:68]: scrollparent https://www.npmjs.com/package/scrollparent is very widely used and stable (363,995 Weekly Downloads) I don't see the benefit of copying scrollparent's code to this repository

File: src/VirtualGrid.vue (hunk 1 above)
Comment (gaodeng) [reply src/VirtualGrid.vue:439]: This will make it easier to add some styles to each item (For example, adjusting the zIndex when hovering). Of course, it can be done without it, but it's easier.

Comment (Mikescops) [reply src/VirtualGrid.vue:439]:
```suggestion
                class="grid-item-wrapper"
```
ok works for me

File: src/VirtualGrid.vue (hunk 3 above)
Comment (gaodeng) [reply src/VirtualGrid.vue:400]: It's not uncommon to see this design pattern of scrolling divs, rather than scrolling the whole page. For example, spotify  https://open.spotify.com/show/3IM0lmZxpFAY7CwMuv9H4g This page actually scrolls the div, not the whole page

File: package.json (hunk 2 above)
Comment (Mikescops) [reply package.json:68]: I want the library to be self-contained

File: src/VirtualGrid.vue (hunk 3 above)
Comment (Mikescops) [reply src/VirtualGrid.vue:400]: oh sorry, i meant to add to the current example a version with a scrolling div, unfortunately i didn't had enough time to add proper testing to the project, so the demo is only proof it works well  :s

Comment (gaodeng) [reply src/VirtualGrid.vue:400]: I should be able to find time to make the relevant changes this week.
Sorry, English is not my native language and I misunderstood you.

Comment (Mikescops) [reply src/VirtualGrid.vue:400]: Me neither, no worries, ok sure, take your time :)

**Comment by Mikescops** [comment]
I have to try your changes, but sounds great!

**Comment by Mikescops** [comment]
Thanks for your contribution, the new version is released.
